type BetInput={ownerKey:string;gameId:number;gameDate:string;startsAt:string|null;matchup:string;market:string;selection:string;line:number|null;americanOdds:number;oppositeOdds:number;modelProbability:number;marketProbability:number;edge:number;expectedValue:number;stakeUnits:number};
const ownerPattern=/^[a-zA-Z0-9-]{20,80}$/;
function valid(input:BetInput){return ownerPattern.test(input.ownerKey)&&Number.isInteger(input.gameId)&&input.gameId>0&&/^\d{4}-\d{2}-\d{2}$/.test(input.gameDate)&&input.matchup.length<=100&&input.market.length<=30&&input.selection.length<=120&&Math.abs(input.americanOdds)>=100&&Math.abs(input.oppositeOdds)>=100&&input.modelProbability>0&&input.modelProbability<1&&input.marketProbability>0&&input.marketProbability<1&&input.edge>=0.025&&input.expectedValue>0.02&&input.stakeUnits>0&&input.stakeUnits<=0.005;}
async function database(){const {env}=await import("cloudflare:workers");return env.DB;}

export async function GET(request:Request){const ownerKey=new URL(request.url).searchParams.get("ownerKey")??"";if(!ownerPattern.test(ownerKey))return Response.json({error:"Invalid ledger key."},{status:400});const db=await database();const result=await db.prepare("SELECT * FROM tracked_bets WHERE owner_key = ? ORDER BY created_at DESC LIMIT 100").bind(ownerKey).all();return Response.json({bets:result.results});}

export async function POST(request:Request){let input:BetInput;try{input=await request.json() as BetInput;}catch{return Response.json({error:"Invalid JSON."},{status:400});}if(!valid(input))return Response.json({error:"Recommendation failed validation or safety gates."},{status:400});const id=crypto.randomUUID(),createdAt=new Date().toISOString(),db=await database();await db.prepare("INSERT INTO tracked_bets (id,owner_key,game_id,game_date,starts_at,matchup,market,selection,line,american_odds,opposite_odds,model_probability,market_probability,edge,expected_value,stake_units,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,input.ownerKey,input.gameId,input.gameDate,input.startsAt,input.matchup,input.market,input.selection,input.line,input.americanOdds,input.oppositeOdds,input.modelProbability,input.marketProbability,input.edge,input.expectedValue,input.stakeUnits,"OPEN",createdAt).run();return Response.json({bet:{id,...input,status:"OPEN",createdAt}},{status:201});}

export async function DELETE(request:Request){const url=new URL(request.url),ownerKey=url.searchParams.get("ownerKey")??"",id=url.searchParams.get("id")??"";if(!ownerPattern.test(ownerKey)||!id)return Response.json({error:"Invalid request."},{status:400});const db=await database();await db.prepare("DELETE FROM tracked_bets WHERE id = ? AND owner_key = ? AND status = 'OPEN'").bind(id,ownerKey).run();return Response.json({ok:true});}
