import { gradeBet, type FinalGame, type SettlementInput } from "@/lib/settlement";
import { closingLineValue } from "@/lib/modeling";
import { portfolioDecision, type PortfolioPosition } from "@/lib/risk";
type BetInput={ownerKey:string;gameId:number;gameDate:string;startsAt:string|null;matchup:string;market:string;selection:string;selectionKey:string;subjectId:number|null;line:number|null;americanOdds:number;oppositeOdds:number;modelProbability:number;marketProbability:number;edge:number;expectedValue:number;stakeUnits:number};
const ownerPattern=/^[a-zA-Z0-9-]{20,80}$/;
function valid(input:BetInput){return typeof input?.ownerKey==="string"&&ownerPattern.test(input.ownerKey)&&Number.isInteger(input.gameId)&&input.gameId>0&&typeof input.gameDate==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(input.gameDate)&&(input.startsAt==null||typeof input.startsAt==="string"&&Number.isFinite(Date.parse(input.startsAt)))&&typeof input.matchup==="string"&&input.matchup.length<=100&&typeof input.market==="string"&&input.market.length<=30&&typeof input.selection==="string"&&input.selection.length<=120&&typeof input.selectionKey==="string"&&input.selectionKey.length<=20&&Math.abs(input.americanOdds)>=100&&Math.abs(input.oppositeOdds)>=100&&input.modelProbability>0&&input.modelProbability<1&&input.marketProbability>0&&input.marketProbability<1&&input.edge>=0.025&&input.expectedValue>0.02&&input.stakeUnits>0&&input.stakeUnits<=0.005;}
async function database(){const {env}=await import("cloudflare:workers");return env.DB;}

export async function GET(request:Request){const ownerKey=new URL(request.url).searchParams.get("ownerKey")??"";if(!ownerPattern.test(ownerKey))return Response.json({error:"Invalid ledger key."},{status:400});const db=await database();const result=await db.prepare("SELECT * FROM tracked_bets WHERE owner_key = ? ORDER BY created_at DESC LIMIT 100").bind(ownerKey).all();return Response.json({bets:result.results});}

export async function POST(request:Request){let input:BetInput;try{input=await request.json() as BetInput;}catch{return Response.json({error:"Invalid JSON."},{status:400});}if(!valid(input))return Response.json({error:"Recommendation failed validation or safety gates."},{status:400});if(input.startsAt&&Date.now()>=Date.parse(input.startsAt))return Response.json({error:"Recommendations lock at scheduled first pitch."},{status:409});const db=await database(),query=await db.prepare("SELECT game_id, game_date, market, selection_key, line, stake_units FROM tracked_bets WHERE owner_key = ? AND status = 'OPEN'").bind(input.ownerKey).all<{game_id:number;game_date:string;market:string;selection_key:string|null;line:number|null;stake_units:number}>(),open:PortfolioPosition[]=(query.results??[]).map(row=>({gameId:row.game_id,gameDate:row.game_date,market:row.market,selectionKey:row.selection_key,line:row.line,stakeUnits:row.stake_units})),portfolio=portfolioDecision(open,{gameId:input.gameId,gameDate:input.gameDate,market:input.market,selectionKey:input.selectionKey,line:input.line,stakeUnits:input.stakeUnits});if(!portfolio.qualifies)return Response.json({error:portfolio.reason,portfolio},{status:409});const id=crypto.randomUUID(),createdAt=new Date().toISOString();await db.prepare("INSERT INTO tracked_bets (id,owner_key,game_id,game_date,starts_at,matchup,market,selection,selection_key,subject_id,line,american_odds,opposite_odds,model_probability,market_probability,edge,expected_value,stake_units,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,input.ownerKey,input.gameId,input.gameDate,input.startsAt,input.matchup,input.market,input.selection,input.selectionKey,input.subjectId,input.line,input.americanOdds,input.oppositeOdds,input.modelProbability,input.marketProbability,input.edge,input.expectedValue,input.stakeUnits,"OPEN",createdAt).run();return Response.json({bet:{id,...input,status:"OPEN",createdAt},portfolio},{status:201});}

export async function DELETE(request:Request){const url=new URL(request.url),ownerKey=url.searchParams.get("ownerKey")??"",id=url.searchParams.get("id")??"";if(!ownerPattern.test(ownerKey)||!id)return Response.json({error:"Invalid request."},{status:400});const db=await database();await db.prepare("DELETE FROM tracked_bets WHERE id = ? AND owner_key = ? AND status = 'OPEN'").bind(id,ownerKey).run();return Response.json({ok:true});}

export async function PUT(request:Request){let input:{ownerKey?:string;id?:string;closingOdds?:number;closingOppositeOdds?:number};try{input=await request.json() as typeof input;}catch{return Response.json({error:"Invalid JSON."},{status:400});}const ownerKey=input.ownerKey??"",id=input.id??"",closingOdds=Number(input.closingOdds),closingOppositeOdds=Number(input.closingOppositeOdds);if(!ownerPattern.test(ownerKey)||!id||Math.abs(closingOdds)<100||Math.abs(closingOppositeOdds)<100)return Response.json({error:"Enter valid two-sided American closing odds."},{status:400});const db=await database(),row=await db.prepare("SELECT market_probability, starts_at FROM tracked_bets WHERE id = ? AND owner_key = ?").bind(id,ownerKey).first<{market_probability:number;starts_at:string|null}>();if(!row)return Response.json({error:"Recommendation not found."},{status:404});if(row.starts_at&&Date.now()>=new Date(row.starts_at).getTime())return Response.json({error:"Closing prices are locked after scheduled first pitch."},{status:409});const clv=closingLineValue(row.market_probability,closingOdds,closingOppositeOdds);if(!clv)return Response.json({error:"Unable to remove vig from those prices."},{status:400});const capturedAt=new Date().toISOString();await db.prepare("UPDATE tracked_bets SET closing_odds = ?, closing_opposite_odds = ?, closing_probability = ?, closing_line_value = ?, closing_captured_at = ? WHERE id = ? AND owner_key = ?").bind(closingOdds,closingOppositeOdds,clv.closingProbability,clv.value,capturedAt,id,ownerKey).run();return Response.json({closingProbability:clv.closingProbability,closingLineValue:clv.value,capturedAt});}

type OpenRow=SettlementInput&{id:string;game_id:number;market:string;selection_key:string|null;subject_id:number|null;american_odds:number;stake_units:number};
type Feed={gameData?:{status?:{abstractGameState?:string}};liveData?:{linescore?:{teams?:{away?:{runs?:number};home?:{runs?:number}};innings?:Array<{num?:number;away?:{runs?:number};home?:{runs?:number}}>};boxscore?:{teams?:{away?:{players?:Record<string,{person?:{id?:number};stats?:{batting?:{hits?:number};pitching?:{strikeOuts?:number}}}>};home?:{players?:Record<string,{person?:{id?:number};stats?:{batting?:{hits?:number};pitching?:{strikeOuts?:number}}}>}}}}};
export async function PATCH(request:Request){let ownerKey="";try{ownerKey=((await request.json()) as {ownerKey?:string}).ownerKey??"";}catch{return Response.json({error:"Invalid JSON."},{status:400});}if(!ownerPattern.test(ownerKey))return Response.json({error:"Invalid ledger key."},{status:400});const db=await database();const query=await db.prepare("SELECT * FROM tracked_bets WHERE owner_key = ? AND status = 'OPEN' AND selection_key IS NOT NULL").bind(ownerKey).all<OpenRow>();const rows=query.results??[],gameIds=[...new Set(rows.map(row=>row.game_id))],feeds=new Map<number,Feed>();await Promise.all(gameIds.map(async gameId=>{const response=await fetch(`https://statsapi.mlb.com/api/v1.1/game/${gameId}/feed/live`,{headers:{accept:"application/json"}});if(response.ok)feeds.set(gameId,await response.json() as Feed);}));const updates=[];for(const row of rows){const feed=feeds.get(row.game_id);if(feed?.gameData?.status?.abstractGameState!=="Final")continue;const linescore=feed.liveData?.linescore,players:FinalGame["players"]={};for(const side of [feed.liveData?.boxscore?.teams?.away,feed.liveData?.boxscore?.teams?.home])for(const player of Object.values(side?.players??{})){const id=player.person?.id;if(id)players[id]={hits:player.stats?.batting?.hits??0,strikeOuts:player.stats?.pitching?.strikeOuts??0};}const finalGame:FinalGame={awayRuns:linescore?.teams?.away?.runs??0,homeRuns:linescore?.teams?.home?.runs??0,innings:(linescore?.innings??[]).map(inning=>({num:inning.num??0,awayRuns:inning.away?.runs??0,homeRuns:inning.home?.runs??0})),players};const grade=gradeBet({market:row.market,selectionKey:row.selection_key,subjectId:row.subject_id,line:row.line,americanOdds:row.american_odds,stakeUnits:row.stake_units},finalGame);if(grade)updates.push(db.prepare("UPDATE tracked_bets SET status = ?, profit_units = ?, settled_at = ? WHERE id = ? AND owner_key = ? AND status = 'OPEN'").bind(grade.result,grade.profitUnits,new Date().toISOString(),row.id,ownerKey));}if(updates.length)await db.batch(updates);return Response.json({checked:rows.length,settled:updates.length});}
