"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { priceDecision } from "@/lib/modeling";

type Team = { name:string; abbreviation:string; probablePitcher:string|null; expectedRuns:number; winProbability:number; fairPrice:string };
type ProjectionGame = { id:number; startsAt:string|null; status:string; venue:string; uncertainty:number; away:Team; home:Team; total:{line:number;expectedRuns:number;overProbability:number;underProbability:number}; drivers:string[]; recommendation:{reason:string} };
type ApiResponse = { games:ProjectionGame[]; retrievedAt:string; error?:string; model?:{name:string;calibrated:boolean;omissions:string[]} };
type Backtest = { gamesIngested:number; through:string; metrics:{count:number;accuracy:number|null;brier:number|null;logLoss:number|null;totalMae:number|null}; calibration:Array<{low:number;high:number;count:number;predicted:number|null;actual:number|null}>; error?:string };

function shiftDate(date:string, amount:number) { const next=new Date(`${date}T12:00:00Z`); next.setUTCDate(next.getUTCDate()+amount); return next.toISOString().slice(0,10); }
function time(value:string|null) { return value ? new Intl.DateTimeFormat("en-US",{hour:"numeric",minute:"2-digit",timeZoneName:"short"}).format(new Date(value)) : "Time TBD"; }
function Ring({value}:{value:number}) { return <span className="confidence" style={{"--score":`${value*3.6}deg`} as React.CSSProperties}><span>{value}</span></span>; }

export function Dashboard() {
  const [date,setDate]=useState(()=>new Date().toISOString().slice(0,10));
  const [games,setGames]=useState<ProjectionGame[]>([]);
  const [selected,setSelected]=useState<number|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState<string|null>(null);
  const [updated,setUpdated]=useState<string|null>(null);
  const [navOpen,setNavOpen]=useState(false);
  const [marketPrice,setMarketPrice]=useState("-110");
  const [bankroll,setBankroll]=useState("1000");
  const [backtest,setBacktest]=useState<Backtest|null>(null);
  const active=useMemo(()=>games.find(game=>game.id===selected)??games[0]??null,[games,selected]);
  const priced=useMemo(()=>{
    if(!active) return null;
    const side=active.home.winProbability>=active.away.winProbability?active.home:active.away;
    const odds=Number(marketPrice);
    const decision=priceDecision(side.winProbability,odds,active.uncertainty/100);
    return decision?{side,odds,...decision}:null;
  },[active,marketPrice]);
  const load=useCallback(async()=>{ setLoading(true); setError(null); try { const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10); const through=date<yesterday?date:yesterday; const [response,historyResponse]=await Promise.all([fetch(`/api/mlb/projections?date=${date}`,{cache:"no-store"}),fetch(`/api/mlb/backtest?through=${through}`,{cache:"no-store"})]); const payload=await response.json() as ApiResponse; if(!response.ok||payload.error) throw new Error(payload.error??"Unable to load projections"); setGames(payload.games); setUpdated(payload.retrievedAt); setSelected(current=>payload.games.some(game=>game.id===current)?current:payload.games[0]?.id??null); if(historyResponse.ok){const history=await historyResponse.json() as Backtest;setBacktest(history);} } catch(reason) { setGames([]); setError(reason instanceof Error?reason.message:"Unable to load projections"); } finally { setLoading(false); } },[date]);
  useEffect(()=>{void load();},[load]);

  return <main className="app-shell">
    <aside className={`sidebar ${navOpen?"open":""}`}><div className="logo"><span className="logo-mark">B</span><span>BASELINE</span></div><nav aria-label="Primary navigation"><a className="nav-link active" href="#slate">Today</a><a className="nav-link" href="#models">Models</a><a className="nav-link" href="#data">Data health</a><a className="nav-link" href="#performance">Performance</a></nav><div className="sidebar-foot"><div className="system-dot"><i/> Experimental model online</div><div className="user-chip"><span>DB</span><small>Daniel’s workspace</small></div></div></aside>
    <section className="workspace"><header className="topbar"><button className="menu" onClick={()=>setNavOpen(!navOpen)} aria-label="Toggle navigation">☰</button><div><p className="eyebrow">MLB ANALYSIS WORKSPACE</p><h1>Daily slate</h1></div><div className="top-actions"><button className="ghost-button">Methodology</button><button className="primary-button" onClick={()=>void load()} disabled={loading}>↻ {loading?"Refreshing…":"Refresh data"}</button></div></header>
      <div className="notice" role="status"><span>✓</span><div><strong>Official MLB data + transparent baseline</strong><p>These are experimental estimates, not picks. No wager qualifies without verified market odds.</p></div></div>
      <section className="live-slate"><div className="section-head live-head"><div><p className="eyebrow">OFFICIAL SCHEDULE + MODEL</p><h2>Games for {date}</h2></div><div className="date-controls"><button onClick={()=>setDate(shiftDate(date,-1))} aria-label="Previous day">←</button><input type="date" value={date} onChange={event=>setDate(event.target.value)} aria-label="Schedule date"/><button onClick={()=>setDate(shiftDate(date,1))} aria-label="Next day">→</button></div></div>
        {loading?<div className="slate-state"><i className="loading-mark"/>Loading MLB data and calculating games…</div>:error?<div className="slate-state error"><strong>Live model unavailable</strong><span>{error}</span><button onClick={()=>void load()}>Try again</button></div>:games.length===0?<div className="slate-state">No MLB games are scheduled for this date.</div>:<div className="game-strip">{games.map(game=><button className={`game-tile game-button ${selected===game.id?"active":""}`} key={game.id} onClick={()=>setSelected(game.id)}><div className="game-status"><span>{game.status}</span><time>{time(game.startsAt)}</time></div><div className="club-row"><strong>{game.away.abbreviation}</strong><span>{game.away.name}</span><em>{game.away.expectedRuns}</em></div><div className="club-row"><strong>{game.home.abbreviation}</strong><span>{game.home.name}</span><em>{game.home.expectedRuns}</em></div><div className="pitchers"><span>{game.away.probablePitcher??"Starter TBD"}</span><b>vs</b><span>{game.home.probablePitcher??"Starter TBD"}</span></div><small>{game.venue}</small></button>)}</div>}
        <div className="live-foot"><span><i/> MLB Stats API · Team Run Baseline v0.1</span><span>{updated?`Updated ${new Date(updated).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}`:"Waiting for source"}</span></div></section>
      <section className="hero-grid" id="slate"><article className="slate-card"><div className="section-head"><div><p className="eyebrow">EXPERIMENTAL BASELINE</p><h2>Model leans—not recommendations</h2></div><span className="model-badge">UNCALIBRATED</span></div><div className="pick-table"><div className="table-row table-header"><span>Game / lean</span><span>Win prob.</span><span>Fair line</span><span>Exp. total</span><span>Action</span></div>{games.map(game=>{const side=game.home.winProbability>=game.away.winProbability?game.home:game.away;return <button className={`table-row ${selected===game.id?"selected":""}`} key={game.id} onClick={()=>setSelected(game.id)}><span className="selection"><i className="team-badge navy">{side.abbreviation}</i><span><strong>{side.name}</strong><small>{game.away.abbreviation} @ {game.home.abbreviation}</small></span></span><span className="mono">{(side.winProbability*100).toFixed(1)}%</span><span className="mono">{side.fairPrice}</span><span className="mono">{game.total.expectedRuns}</span><span className="no-bet">NO BET</span></button>})}</div><div className="table-foot"><span><i className="quality-dot"/> Team scoring, prevention, home field, score distribution</span><span>Market odds required</span></div></article>
        <aside className="explain-card">{active?<><div className="explain-top"><div><p className="eyebrow">MATCHUP + PRICE LAB</p><h3>{active.away.abbreviation} at {active.home.abbreviation}</h3><p>{time(active.startsAt)} · {active.venue}</p></div><Ring value={100-active.uncertainty}/></div><div className="price-grid"><div><small>AWAY WIN</small><strong>{(active.away.winProbability*100).toFixed(1)}%</strong></div><div><small>HOME WIN</small><strong>{(active.home.winProbability*100).toFixed(1)}%</strong></div><div><small>EXPECTED SCORE</small><strong>{active.away.expectedRuns}–{active.home.expectedRuns}</strong></div></div><div className="driver-list">{active.drivers.map((driver,index)=><div key={driver}><span>{index+1}</span><div><strong>{index===2?"League environment":"Season scoring"}</strong><p>{driver}</p></div></div>)}</div><div className="odds-lab"><div className="odds-title"><div><small>MANUAL MARKET CHECK</small><strong>{priced?.side.name} moneyline</strong></div><span>Fair {priced?.side.fairPrice}</span></div><div className="odds-inputs"><label>Sportsbook odds<input inputMode="numeric" value={marketPrice} onChange={event=>setMarketPrice(event.target.value)} aria-label="American sportsbook odds"/></label><label>Bankroll ($)<input inputMode="decimal" value={bankroll} onChange={event=>setBankroll(event.target.value)} aria-label="Bankroll in dollars"/></label></div>{priced?<div className={`decision ${priced.qualifies?"qualifies":"pass"}`}><div><small>MARKET IMPLIED</small><strong>{(priced.marketProbability*100).toFixed(1)}%</strong></div><div><small>MODEL EDGE</small><strong>{priced.edge>=0?"+":""}{(priced.edge*100).toFixed(1)}%</strong></div><div><small>EXPECTED ROI</small><strong>{priced.expectedValue>=0?"+":""}{(priced.expectedValue*100).toFixed(1)}%</strong></div><div><small>MAX STAKE</small><strong>{priced.qualifies?`$${(Number(bankroll||0)*priced.stakeFraction).toFixed(2)}`:"$0"}</strong></div><p>{priced.qualifies?"Price passes the 2.5% edge, positive-EV and uncertainty gates. Stake is capped at 0.5% of bankroll.":"PASS — this price does not clear every safety gate. No wager recommended."}</p></div>:<p className="input-help">Enter valid American odds of +100 or longer, or −100 or shorter.</p>}</div><div className="caution"><span>!</span><p><strong>Experimental only</strong>Manual odds are not persisted or verified. Starter quality, lineups, bullpen, park and weather are not yet included.</p></div></>:<div className="slate-state">Select a game to inspect the model.</div>}</aside></section>
      <section className="metric-row" id="performance"><article><div><p className="eyebrow">WALK-FORWARD ACCURACY</p><strong>{backtest?.metrics.accuracy!=null?`${(backtest.metrics.accuracy*100).toFixed(1)}%`:"—"}</strong></div><small>{backtest?.metrics.count??0} out-of-sample games</small></article><article><div><p className="eyebrow">BRIER SCORE</p><strong>{backtest?.metrics.brier?.toFixed(3)??"—"}</strong></div><small>Lower is better · 0.250 naive baseline</small></article><article><div><p className="eyebrow">TOTAL RUN MAE</p><strong>{backtest?.metrics.totalMae?.toFixed(2)??"—"}</strong></div><small>Average absolute runs error</small></article><article><div><p className="eyebrow">OPEN EXPOSURE</p><strong>0.0u</strong></div><span className="exposure">SAFE</span><small>No saved wagers</small></article></section>
      {backtest&&<section className="performance-panel"><div className="section-head"><div><p className="eyebrow">HONEST HISTORICAL VALIDATION</p><h2>Calibration by predicted home-win probability</h2></div><span className="model-badge">THROUGH {backtest.through}</span></div><div className="calibration-grid">{backtest.calibration.map(bucket=><div className="calibration-row" key={bucket.low}><span>{Math.round(bucket.low*100)}–{Math.round(bucket.high*100)}%</span><div className="calibration-track"><i style={{width:`${(bucket.predicted??0)*100}%`}}/><b style={{left:`${(bucket.actual??0)*100}%`}}/></div><strong>{bucket.count?`${((bucket.actual??0)*100).toFixed(0)}% actual`:"No games"}</strong><small>n={bucket.count}</small></div>)}</div><div className="performance-foot"><span>{backtest.gamesIngested} final games ingested from MLB</span><span>Expanding window · 10 prior games required · no future games used</span></div></section>}
      <section className="lower-grid"><article className="panel" id="models"><div className="section-head"><div><p className="eyebrow">MODEL CONTROL</p><h2>What is modeled now</h2></div></div><div className="check-list"><div><span className="check-icon good">✓</span><div><strong>Time-safe season baselines</strong><p>Runs scored and allowed through the selected season</p></div><em>ACTIVE</em></div><div><span className="check-icon good">✓</span><div><strong>Score distribution</strong><p>Poisson outcomes convert expected runs into win and total probabilities</p></div><em>ACTIVE</em></div><div><span className="check-icon warn">!</span><div><strong>Calibration</strong><p>Probabilities are not certified until historical backtesting is complete</p></div><em>PENDING</em></div></div></article><article className="panel" id="data"><div className="section-head"><div><p className="eyebrow">DATA LINEAGE</p><h2>Source health</h2></div><span className="live-tag"><i/> LIVE</span></div><div className="source-list"><div><span className="source-icon">MLB</span><div><strong>Official MLB feed</strong><p>Schedule · probable pitchers · standings · run totals</p></div><span className="source-state healthy">live</span></div><div><span className="source-icon">$</span><div><strong>Sportsbook prices</strong><p>Adapter and manual entry are the next build stage</p></div><span className="source-state review">needed</span></div><div><span className="source-icon">WX</span><div><strong>Context feeds</strong><p>Weather · parks · lineups · bullpen availability</p></div><span className="source-state review">pending</span></div></div></article></section>
      <footer><span>Baseline v0.4 · Walk-forward validation</span><span>Probabilities are estimates, not guarantees. Bet responsibly.</span></footer></section>
  </main>;
}
