import { countOverProbability, fairAmerican, strikeoutOverProbability } from "./modeling.ts";

export type PickCategory="SIDE"|"RUN LINE"|"TOTAL"|"TEAM TOTAL"|"F5"|"1ST INNING"|"PITCHER K"|"HITTER";
export type DailyPick={id:string;gameId:number;matchup:string;startsAt:string|null;market:PickCategory;selection:string;probability:number;rawProbability:number;fairPrice:string;explanation:string;recommended:boolean;validated:boolean;uncertainty:number;inputNote:string};
type Hitter={id:number;name:string;onePlusHitProbability:number|null;fairPrice:string|null};
type Side={name:string;abbreviation:string;expectedRuns:number;winProbability:number;fairPrice:string;starter:{expectedStrikeouts:number|null}|null};
type PickGame={id:number;startsAt:string|null;uncertainty:number;away:Side;home:Side;total:{line:number;expectedRuns:number;overProbability:number;underProbability:number;overFairPrice:string;underFairPrice:string};firstFive:{expectedRuns:number;awayWinProbability:number;homeWinProbability:number;awayFairPrice:string;homeFairPrice:string};firstInning:{nrfiProbability:number;yrfiProbability:number;nrfiFairPrice:string;yrfiFairPrice:string};lineups:{away:Hitter[];home:Hitter[];confirmed:boolean};quality:{teamRecords:boolean;starterStats:boolean;lineups:boolean;bullpen:boolean;weather:boolean;parkSample:boolean;validatedMarkets:{moneyline:boolean;total:boolean;firstFive:boolean;firstInning:boolean;pitcherStrikeouts:boolean;hitterHits:boolean}}};

const THRESHOLD=.55;
function poisson(k:number,lambda:number){let factorial=1;for(let i=2;i<=k;i++)factorial*=i;return Math.exp(-lambda)*lambda**k/factorial}
function runLine(awayRuns:number,homeRuns:number,homeLine:number){let win=0,total=0;for(let a=0;a<=18;a++)for(let h=0;h<=18;h++){const mass=poisson(a,awayRuns)*poisson(h,homeRuns);total+=mass;if(h+homeLine>a)win+=mass}return total?win/total:0}
function pick(shared:Pick<DailyPick,"gameId"|"matchup"|"startsAt"|"uncertainty">,id:string,market:PickCategory,selection:string,rawProbability:number,explanation:string,validated:boolean,inputNote:string):DailyPick{const reliability=Math.max(.25,1-shared.uncertainty/100),probability=.5+(rawProbability-.5)*reliability;return{...shared,id,market,selection,rawProbability,probability,fairPrice:fairAmerican(probability),explanation,validated,inputNote,recommended:probability>=THRESHOLD&&validated}}

export function dailyPicks(games:PickGame[]){const byGame=new Map<number,DailyPick[]>(),all:DailyPick[]=[];for(const game of games){const matchup=`${game.away.abbreviation} @ ${game.home.abbreviation}`,shared={gameId:game.id,matchup,startsAt:game.startsAt,uncertainty:game.uncertainty},inputs=`${game.quality.starterStats?"starters":"starter gap"} · ${game.quality.bullpen?"bullpens":"bullpen gap"} · ${game.quality.weather?"weather":"weather pending"}`,side=game.home.winProbability>=game.away.winProbability?game.home:game.away,totalOver=game.total.overProbability>=game.total.underProbability,f5Home=game.firstFive.homeWinProbability>=game.firstFive.awayWinProbability,firstNrfi=game.firstInning.nrfiProbability>=game.firstInning.yrfiProbability;
    const favoriteHome=game.home.winProbability>=game.away.winProbability,rlProbability=favoriteHome?runLine(game.away.expectedRuns,game.home.expectedRuns,-1.5):1-runLine(game.away.expectedRuns,game.home.expectedRuns,1.5),favorite=favoriteHome?game.home:game.away;
    const awayTeamOver=countOverProbability(game.away.expectedRuns,4.5)??0,homeTeamOver=countOverProbability(game.home.expectedRuns,4.5)??0,teamOver=awayTeamOver>=homeTeamOver,team=teamOver?game.away:game.home,teamProb=teamOver?awayTeamOver:homeTeamOver;
    const f5Over=countOverProbability(game.firstFive.expectedRuns,4.5)??0,f5TotalOver=f5Over>=1-f5Over,f5TotalProb=f5TotalOver?f5Over:1-f5Over;
    const rows:DailyPick[]=[
      pick(shared,`${game.id}-ml`,"SIDE",`${side.abbreviation} moneyline`,side.winProbability,`${side.name} has the stronger win probability; projected score ${game.away.expectedRuns}–${game.home.expectedRuns}.`,game.quality.validatedMarkets.moneyline&&game.quality.starterStats,inputs),
      pick(shared,`${game.id}-rl`,"RUN LINE",`${favorite.abbreviation} -1.5`,rlProbability,`The score distribution estimates the chance ${favorite.name} wins by at least two runs. Margin uses an independent-Poisson approximation without walk-off or extra-innings structure — research only.`,false,`${inputs} · derived score margin`),
      pick(shared,`${game.id}-total`,"TOTAL",`${totalOver?"Over":"Under"} ${game.total.line}`,totalOver?game.total.overProbability:game.total.underProbability,`Projected total ${game.total.expectedRuns} versus the ${game.total.line} line.`,game.quality.validatedMarkets.total&&game.quality.starterStats,inputs),
      pick(shared,`${game.id}-team-total`,"TEAM TOTAL",`${team.abbreviation} over 4.5`,teamProb,`${team.name} projects for ${team.expectedRuns} runs; this estimates 5+ runs. Team run counts are Poisson-approximate — research only.`,false,`${inputs} · team Poisson distribution`),
      pick(shared,`${game.id}-f5`,"F5",`${f5Home?game.home.abbreviation:game.away.abbreviation} first 5 ML`,f5Home?game.firstFive.homeWinProbability:game.firstFive.awayWinProbability,`Favors ${f5Home?game.home.name:game.away.name} through five innings, reducing late-bullpen influence.`,game.quality.validatedMarkets.firstFive&&game.quality.starterStats,inputs),
      pick(shared,`${game.id}-f5-total`,"F5",`F5 ${f5TotalOver?"over":"under"} 4.5`,f5TotalProb,`The first-five model projects ${game.firstFive.expectedRuns} runs.`,false,`${game.quality.starterStats?"both starters":"starter gap"} · empirical F5 run share`),
      pick(shared,`${game.id}-first`,"1ST INNING",firstNrfi?"NRFI":"YRFI",firstNrfi?game.firstInning.nrfiProbability:game.firstInning.yrfiProbability,`${firstNrfi?"No run":"A run"} in the first is the higher-probability starter-adjusted outcome.`,game.quality.validatedMarkets.firstInning&&game.quality.starterStats,`${game.quality.starterStats?"both starters":"starter gap"} · first-inning run share`),
    ];
    for(const [label,club] of [[game.away.abbreviation,game.away],[game.home.abbreviation,game.home]] as const){const mean=club.starter?.expectedStrikeouts,p=mean==null?null:strikeoutOverProbability(mean,5.5);if(p!=null)rows.push(pick(shared,`${game.id}-${label}-k`,"PITCHER K",`${club.name} starter over 5.5 K`,p,`Projected ${mean.toFixed(1)} strikeouts against a 5.5 line.`,game.quality.validatedMarkets.pitcherStrikeouts,`starter K rate · opponent strikeout tendency`))}
    const hitters=[...game.lineups.away,...game.lineups.home].filter(h=>h.onePlusHitProbability!=null).sort((a,b)=>(b.onePlusHitProbability??0)-(a.onePlusHitProbability??0)).slice(0,2);for(const hitter of hitters)rows.push(pick(shared,`${game.id}-${hitter.id}-hit`,"HITTER",`${hitter.name} 1+ hit`,hitter.onePlusHitProbability??0,`Season hit rate, expected at-bats and handedness split produce this estimate.`,game.quality.validatedMarkets.hitterHits&&game.quality.lineups,`confirmed lineup · regressed platoon split`));
    byGame.set(game.id,rows);all.push(...rows)}
  // The recommended list and the per-pick "recommended" flag share one rule:
  // probability threshold AND market-specific validation. Unvalidated leans
  // stay browsable in the per-market views but are never listed as picks.
  const candidates=all.filter(p=>p.probability>=THRESHOLD&&p.validated).sort((a,b)=>Number(b.validated)-Number(a.validated)||b.probability-a.probability||a.uncertainty-b.uncertainty),perGame=new Map<number,number>(),recommended:DailyPick[]=[];for(const row of candidates){if((perGame.get(row.gameId)??0)>=2)continue;recommended.push(row);perGame.set(row.gameId,(perGame.get(row.gameId)??0)+1);if(recommended.length===12)break}return{byGame,all,recommended,categories:[...new Set(all.map(p=>p.market))] as PickCategory[]}}
