type Forecast={game_id:number;market:string;selection_key:string;line:number|null;probability:number;outcome:number;starts_at:string};
type Observation={game_id:number;market:string;selection:string;line:number|null;american_odds:number;observed_at:string;sportsbook:string;metadata_json:string};
type CanonicalObservation=Observation&{canonicalMarket:string;canonicalSelection:string};
const implied=(odds:number)=>odds>0?100/(odds+100):-odds/(-odds+100);
const profit=(odds:number)=>odds>0?odds/100:100/-odds;
const opposite=(selection:string)=>({home:"away",away:"home",over:"under",under:"over",nrfi:"yrfi",yrfi:"nrfi"}[selection]??"");
function normalize(row:Observation):CanonicalObservation|null{let meta={} as Record<string,unknown>;try{meta=JSON.parse(row.metadata_json);}catch{}const canonicalMarket=String(meta.canonicalMarket??row.market).toLowerCase(),raw=String(meta.canonicalSelection??row.selection).toLowerCase(),canonicalSelection=["home","away","over","under","nrfi","yrfi"].find(value=>raw===value||raw.includes(value));if(!canonicalSelection||!["moneyline","over","f5","nrfi","yrfi"].includes(canonicalMarket))return null;return{...row,canonicalMarket,canonicalSelection};}
export function marketValidation(forecasts:Forecast[],rawOdds:Observation[]){const odds=rawOdds.map(normalize).filter((row):row is CanonicalObservation=>Boolean(row)),evaluated=[] as Array<{market:string;edge:number;lineMove:number|null;qualifies:boolean;profit:number;book:string}>;
  for(const forecast of forecasts){const selection=forecast.selection_key,other=opposite(selection),market=forecast.market,books=[...new Set(odds.filter(row=>row.game_id===forecast.game_id&&row.canonicalMarket===market&&(forecast.line==null||row.line==null||Math.abs(row.line-forecast.line)<.01)&&Date.parse(row.observed_at)<Date.parse(forecast.starts_at)).map(row=>row.sportsbook))];let best:null|{selected:CanonicalObservation;other:CanonicalObservation;openSelected:CanonicalObservation;openOther:CanonicalObservation}=null;
    for(const book of books){const rows=odds.filter(row=>row.game_id===forecast.game_id&&row.canonicalMarket===market&&row.sportsbook===book&&(forecast.line==null||row.line==null||Math.abs(row.line-forecast.line)<.01)&&Date.parse(row.observed_at)<Date.parse(forecast.starts_at)).sort((a,b)=>Date.parse(a.observed_at)-Date.parse(b.observed_at)),selectedRows=rows.filter(row=>row.canonicalSelection===selection),otherRows=rows.filter(row=>row.canonicalSelection===other);if(!selectedRows.length||!otherRows.length)continue;const candidate={selected:selectedRows.at(-1)!,other:otherRows.at(-1)!,openSelected:selectedRows[0],openOther:otherRows[0]};if(!best||Date.parse(candidate.selected.observed_at)>Date.parse(best.selected.observed_at))best=candidate;}
    if(!best)continue;const selectedImplied=implied(best.selected.american_odds),otherImplied=implied(best.other.american_odds),marketProbability=selectedImplied/(selectedImplied+otherImplied),openSelected=implied(best.openSelected.american_odds),openOther=implied(best.openOther.american_odds),openProbability=openSelected/(openSelected+openOther),edge=forecast.probability-marketProbability,qualifies=forecast.probability>=.5&&edge>=.03,effectiveProfit=qualifies?(forecast.outcome===1?profit(best.selected.american_odds):-1):0;evaluated.push({market,edge,lineMove:marketProbability-openProbability,qualifies,profit:effectiveProfit,book:best.selected.sportsbook});
  }
  const summarize=(rows:typeof evaluated)=>{const plays=rows.filter(row=>row.qualifies);return{priced:rows.length,qualifying:plays.length,roi:plays.length?plays.reduce((sum,row)=>sum+row.profit,0)/plays.length:null,averageEdge:rows.length?rows.reduce((sum,row)=>sum+row.edge,0)/rows.length:null,averageMarketMove:rows.filter(row=>row.lineMove!=null).length?rows.reduce((sum,row)=>sum+(row.lineMove??0),0)/rows.filter(row=>row.lineMove!=null).length:null};};const markets=[...new Set(forecasts.map(row=>row.market))].map(market=>({market,...summarize(evaluated.filter(row=>row.market===market))}));return{forecasts:forecasts.length,pricedForecasts:evaluated.length,coverage:forecasts.length?evaluated.length/forecasts.length:0,...summarize(evaluated),markets,activation:{minimumPriced:500,minimumPerMarket:100,minimumPositiveRoi:true,ready:evaluated.length>=500&&markets.every(row=>row.priced>=100)&&markets.every(row=>row.roi!=null&&row.roi>0)}};}
