import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = {
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
};

export const teams = sqliteTable("teams", { id: integer("id").primaryKey(), abbreviation: text("abbreviation").notNull(), name: text("name").notNull(), league: text("league").notNull(), division: text("division").notNull(), ...timestamps }, (t) => [uniqueIndex("teams_abbr_uq").on(t.abbreviation)]);
export const players = sqliteTable("players", { id: integer("id").primaryKey(), fullName: text("full_name").notNull(), bats: text("bats"), throws: text("throws"), primaryPosition: text("primary_position"), active: integer("active", { mode: "boolean" }).notNull(), ...timestamps });
export const games = sqliteTable("games", { id: integer("id").primaryKey(), season: integer("season").notNull(), gameDate: text("game_date").notNull(), scheduledAt: text("scheduled_at").notNull(), status: text("status").notNull(), awayTeamId: integer("away_team_id").notNull().references(() => teams.id), homeTeamId: integer("home_team_id").notNull().references(() => teams.id), venueId: integer("venue_id"), awayScore: integer("away_score"), homeScore: integer("home_score"), ...timestamps }, (t) => [index("games_date_idx").on(t.gameDate), index("games_teams_idx").on(t.awayTeamId, t.homeTeamId)]);
export const lineups = sqliteTable("lineups", { id: integer("id").primaryKey({ autoIncrement:true }), gameId: integer("game_id").notNull().references(() => games.id), teamId: integer("team_id").notNull().references(() => teams.id), playerId: integer("player_id").notNull().references(() => players.id), battingOrder: integer("batting_order").notNull(), position: text("position").notNull(), confirmedAt: text("confirmed_at") }, (t) => [uniqueIndex("lineup_slot_uq").on(t.gameId,t.teamId,t.battingOrder)]);
export const pitchingAssignments = sqliteTable("pitching_assignments", { id: integer("id").primaryKey({ autoIncrement:true }), gameId: integer("game_id").notNull().references(() => games.id), teamId: integer("team_id").notNull().references(() => teams.id), playerId: integer("player_id").notNull().references(() => players.id), role: text("role").notNull(), confirmed: integer("confirmed", { mode:"boolean" }).notNull(), expectedPitches: real("expected_pitches"), restDays: integer("rest_days") });
export const sourceSnapshots = sqliteTable("source_snapshots", { id: integer("id").primaryKey({ autoIncrement:true }), source: text("source").notNull(), endpoint: text("endpoint").notNull(), parametersJson: text("parameters_json").notNull(), retrievedAt: text("retrieved_at").notNull(), coverageStart: text("coverage_start"), coverageEnd: text("coverage_end"), rowCount: integer("row_count").notNull(), contentHash: text("content_hash").notNull(), status: text("status").notNull(), validationJson: text("validation_json").notNull() }, (t) => [index("source_time_idx").on(t.source,t.retrievedAt), index("source_hash_idx").on(t.contentHash)]);
export const oddsSnapshots = sqliteTable("odds_snapshots", { id: integer("id").primaryKey({ autoIncrement:true }), gameId: integer("game_id").notNull().references(() => games.id), sportsbook: text("sportsbook").notNull(), market: text("market").notNull(), selection: text("selection").notNull(), line: real("line"), americanOdds: integer("american_odds").notNull(), observedAt: text("observed_at").notNull() }, (t) => [index("odds_lookup_idx").on(t.gameId,t.market,t.observedAt)]);
export const modelRuns = sqliteTable("model_runs", { id: text("id").primaryKey(), modelName: text("model_name").notNull(), modelVersion: text("model_version").notNull(), trainedThrough: text("trained_through").notNull(), generatedAt: text("generated_at").notNull(), featureCutoff: text("feature_cutoff").notNull(), calibrationVersion: text("calibration_version").notNull(), metadataJson: text("metadata_json").notNull() });
export const predictions = sqliteTable("predictions", { id: text("id").primaryKey(), modelRunId: text("model_run_id").notNull().references(() => modelRuns.id), gameId: integer("game_id").notNull().references(() => games.id), market: text("market").notNull(), selection: text("selection").notNull(), line: real("line"), probability: real("probability").notNull(), fairAmericanOdds: integer("fair_american_odds").notNull(), uncertainty: real("uncertainty").notNull(), explanationJson: text("explanation_json").notNull(), generatedAt: text("generated_at").notNull() }, (t) => [index("predictions_game_idx").on(t.gameId,t.market)]);
export const recommendations = sqliteTable("recommendations", { id: text("id").primaryKey(), predictionId: text("prediction_id").notNull().references(() => predictions.id), oddsSnapshotId: integer("odds_snapshot_id").notNull().references(() => oddsSnapshots.id), edge: real("edge").notNull(), expectedValue: real("expected_value").notNull(), maxPlayableOdds: integer("max_playable_odds").notNull(), stakeUnits: real("stake_units").notNull(), decision: text("decision").notNull(), correlationGroup: text("correlation_group").notNull(), createdAt: text("created_at").notNull() });
export const settledResults = sqliteTable("settled_results", { id: integer("id").primaryKey({ autoIncrement:true }), recommendationId: text("recommendation_id").notNull().references(() => recommendations.id), result: text("result").notNull(), profitUnits: real("profit_units").notNull(), closingOdds: integer("closing_odds"), closingLineValue: real("closing_line_value"), settledAt: text("settled_at").notNull() }, (t) => [uniqueIndex("settled_recommendation_uq").on(t.recommendationId)]);
export const trackedBets = sqliteTable("tracked_bets", { id:text("id").primaryKey(), ownerKey:text("owner_key").notNull(), gameId:integer("game_id").notNull(), gameDate:text("game_date").notNull(), startsAt:text("starts_at"), matchup:text("matchup").notNull(), market:text("market").notNull(), selection:text("selection").notNull(), selectionKey:text("selection_key"), subjectId:integer("subject_id"), line:real("line"), americanOdds:integer("american_odds").notNull(), oppositeOdds:integer("opposite_odds").notNull(), maxPlayableOdds:integer("max_playable_odds"), closingOdds:integer("closing_odds"), closingOppositeOdds:integer("closing_opposite_odds"), closingProbability:real("closing_probability"), closingLineValue:real("closing_line_value"), closingCapturedAt:text("closing_captured_at"), modelProbability:real("model_probability").notNull(), marketProbability:real("market_probability").notNull(), edge:real("edge").notNull(), expectedValue:real("expected_value").notNull(), stakeUnits:real("stake_units").notNull(), status:text("status").notNull(), profitUnits:real("profit_units"), createdAt:text("created_at").notNull(), settledAt:text("settled_at") },(t)=>[index("tracked_owner_created_idx").on(t.ownerKey,t.createdAt),index("tracked_open_game_idx").on(t.status,t.gameId)]);

export const forecastSnapshots=sqliteTable("forecast_snapshots",{id:text("id").primaryKey(),gameId:integer("game_id").notNull(),gameDate:text("game_date").notNull(),startsAt:text("starts_at").notNull(),modelVersion:text("model_version").notNull(),market:text("market").notNull(),selectionKey:text("selection_key").notNull(),line:real("line"),probability:real("probability").notNull(),status:text("status").notNull(),outcome:integer("outcome"),brier:real("brier"),createdAt:text("created_at").notNull(),settledAt:text("settled_at")},(t)=>[index("forecast_status_game_idx").on(t.status,t.gameId),index("forecast_market_date_idx").on(t.market,t.gameDate)]);
