import { prospectiveMetrics, type ScoredForecast } from "@/lib/prospective";
import { gradeBet, type FinalGame } from "@/lib/settlement";

type OpenForecast={id:string;game_id:number;market:string;selection_key:string;line:number|null;probability:number};
type ScoredRow={market:string;probability:number;outcome:number;brier:number};
type Feed={gameData?:{status?:{abstractGameState?:string}};liveData?:{linescore?:{teams?:{away?:{runs?:number};home?:{runs?:number}};innings?:Array<{num?:number;away?:{runs?:number};home?:{runs?:number}}>};boxscore?:{teams?:{away?:{players?:Record<string,{person?:{id?:number};stats?:{batting?:{hits?:number};pitching?:{strikeOuts?:number}}}>};home?:{players?:Record<string,{person?:{id?:number};stats?:{batting?:{hits?:number};pitching?:{strikeOuts?:number}}}>}}}}};

export async function GET(){
  try{
  const {env}=await import("cloudflare:workers"),openQuery=await env.DB.prepare("SELECT id,game_id,market,selection_key,line,probability FROM forecast_snapshots WHERE status = 'OPEN' AND starts_at < ? ORDER BY starts_at LIMIT 240").bind(new Date().toISOString()).all<OpenForecast>(),open=openQuery.results??[],feeds=new Map<number,Feed>(),gameIds=[...new Set(open.map(row=>row.game_id))];
  await Promise.all(gameIds.map(async gameId=>{try{const response=await fetch(`https://statsapi.mlb.com/api/v1.1/game/${gameId}/feed/live`,{headers:{accept:"application/json"}});if(response.ok)feeds.set(gameId,await response.json() as Feed);}catch{/* A later request retries unsettled games. */}}));
  const updates=[];for(const row of open){const feed=feeds.get(row.game_id);if(feed?.gameData?.status?.abstractGameState!=="Final")continue;const linescore=feed.liveData?.linescore,players:FinalGame["players"]={};for(const side of [feed.liveData?.boxscore?.teams?.away,feed.liveData?.boxscore?.teams?.home])for(const player of Object.values(side?.players??{})){const id=player.person?.id;if(id)players[id]={hits:player.stats?.batting?.hits??0,strikeOuts:player.stats?.pitching?.strikeOuts??0};}const finalGame:FinalGame={awayRuns:linescore?.teams?.away?.runs??0,homeRuns:linescore?.teams?.home?.runs??0,innings:(linescore?.innings??[]).map(inning=>({num:inning.num??0,awayRuns:inning.away?.runs??0,homeRuns:inning.home?.runs??0})),players},grade=gradeBet({market:row.market,selectionKey:row.selection_key,subjectId:null,line:row.line,americanOdds:100,stakeUnits:1},finalGame);if(!grade)continue;const outcome=grade.result==="WON"?1:grade.result==="LOST"?0:null,brier=outcome==null?null:(row.probability-outcome)**2;updates.push(env.DB.prepare("UPDATE forecast_snapshots SET status = ?, outcome = ?, brier = ?, settled_at = ? WHERE id = ? AND status = 'OPEN'").bind(grade.result,outcome,brier,new Date().toISOString(),row.id));}
  if(updates.length)await env.DB.batch(updates);
  const scoredQuery=await env.DB.prepare("SELECT market,probability,outcome,brier FROM forecast_snapshots WHERE status IN ('WON','LOST') ORDER BY game_date DESC LIMIT 10000").all<ScoredRow>(),statusQuery=await env.DB.prepare("SELECT status, COUNT(*) AS count FROM forecast_snapshots GROUP BY status").all<{status:string;count:number}>(),rows=(scoredQuery.results??[]) as ScoredForecast[],status=Object.fromEntries((statusQuery.results??[]).map(row=>[row.status,row.count]));
  return Response.json({retrievedAt:new Date().toISOString(),issued:Object.values(status).reduce((sum,count)=>sum+count,0),status,settledNow:updates.length,...prospectiveMetrics(rows)},{headers:{"cache-control":"no-store"}});
  }catch(error){const detail=error instanceof Error?error.message:"Unknown database error";return Response.json({error:"Prospective tracking is initializing.",detail},{status:503,headers:{"cache-control":"no-store"}});}
}
